// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  THE MARK, AND THE GEOMETRY IT IS BUILT FROM                             ║
// ╚══════════════════════════════════════════════════════════════════════════╝
//
// Moved out of art.jsx whole, and for one reason: the logo exports in
// design/logo are generated by scripts/export-mark.mjs, node cannot read JSX,
// and a second copy of these constants in the exporter is a second copy that
// drifts. Now the drawing on the screen, the drawing in the tab, and the
// drawing in the PNG a printer is handed all come out of this file.
//
// Nothing here changed in the move. art.jsx re-exports every name below, so
// every existing import of it still resolves.
//
// design/DESIGN.md section 3 is the prose account of what this draws.

// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  ECLIPTIC — THE MARK                                                     ║
// ╚══════════════════════════════════════════════════════════════════════════╝
//
// The four-point star of SPARK, drawn slim, inside a ring that passes behind it
// at the top and in front of it at the bottom. One object rather than two, and
// the only place in the build where anything crosses anything.
//
// ── the ring is a true annulus first, and modulated second ──────────────────
// A flat ring tilted away from you projects BOTH of its edges by the same
// cosine, so the band reads full width at the ends of the long axis and
// foreshortened where it crosses the body. Adding the band's width to the short
// axis un-scaled instead makes it four and a half times too fat at exactly the
// point it passes over the star — and a band that is widest where it crosses is
// a ribbon lying on the mark, not a ring going round it. It also forces a fat
// gutter to keep the star readable underneath, and that gap is what makes the
// two read as separate objects.
//
// Drawn honestly the band already varies two to one round the ring. BIAS then
// pushes the inner edge to the far side so the near half runs wider still, and
// TWIST turns it so the widest part walks. Together, about three to one.
//
// Two limits, and both are geometry rather than taste. The inner edge must stay
// inside the outer or the band breaks open: past roughly bias 2 or twist 10 it
// does. And every arm must finish clear of the band, because an arm that ENDS
// inside the band gets notched off and left as a floating tip. On the shipped
// constants the edges come closest at 0.075, the side arms sit at 0.55 of the
// hole, and the vertical arms clear the outer edge by 3.86.
export const ECL = {
  rx: 42,          // the ring, to the middle of its band
  flat: 0.5,       // ry/rx — the viewing angle, applied to BOTH edges
  tilt: -19,       // degrees off horizontal
  w: 3.2,          // half the band's width in the ring's own plane
  bias: 1.2,       // the inner edge pushed toward the far side, so the near
                   // half of the band runs wider than the far half
  twist: 2,        // and turned a little, so the widest part walks round
  gutter: 0.7,     // the void between the ring and the star it crosses
  up: 47, down: 47, side: 24,
  thick: 0.8,      // how much body the arms carry. 1 is SPARK exactly; each
                   // step up peels the curve off its axis sooner, and past
                   // about 1.4 the concave flattens and the star goes diamond
}

// SPARK's own control points, as fractions of each arm: `along` is how far back
// along its own radius the control beside a vertex sits, `lean` is how far it
// leans toward the neighbour it faces.
const K = { along: 0.42, lean: 0.03, sideAlong: 0.24, sideLean: 0.19 }

export const f2 = (v) => Math.round(v * 100) / 100
export const rad = (d) => (d * Math.PI) / 180

// Four vertices, four cubics, and no corner anywhere in it. Each control is
// built only from its own vertex's radius and its neighbour's DIRECTION —
// scaling the lean by the neighbour's radius instead makes a short vertex pull
// harder than a long one, which is its own source of lumpiness on a star whose
// arms are not equal.
export function starPath(o) {
  const ax = { along: K.along * o.thick, lean: K.lean }
  const sd = { along: K.sideAlong * o.thick, lean: K.sideLean }
  const V = [{ a: -90, r: o.up, k: ax }, { a: 0, r: o.side, k: sd },
             { a: 90, r: o.down, k: ax }, { a: 180, r: o.side, k: sd }]
  const dir = (v) => [Math.cos(rad(v.a)), Math.sin(rad(v.a))]
  for (let i = 0; i < 4; i++) {
    const v = V[i], prev = V[(i + 3) % 4], next = V[(i + 1) % 4]
    const d = dir(v), dn = dir(next), dp = dir(prev)
    v.p = [d[0] * v.r, d[1] * v.r]
    v.out = [d[0] * v.r * v.k.along + dn[0] * v.r * v.k.lean,
             d[1] * v.r * v.k.along + dn[1] * v.r * v.k.lean]
    v.in = [d[0] * v.r * v.k.along + dp[0] * v.r * v.k.lean,
            d[1] * v.r * v.k.along + dp[1] * v.r * v.k.lean]
  }
  let d = `M${f2(V[0].p[0])} ${f2(V[0].p[1])}`
  for (let i = 0; i < 4; i++) {
    const A = V[i], B = V[(i + 1) % 4]
    d += `C${f2(A.out[0])} ${f2(A.out[1])} ${f2(B.in[0])} ${f2(B.in[1])} ${f2(B.p[0])} ${f2(B.p[1])}`
  }
  return d + 'Z'
}

function ellipse(cx, cy, a, b, tilt) {
  const t = rad(tilt), dx = a * Math.cos(t), dy = a * Math.sin(t)
  const arc = `A${f2(a)} ${f2(b)} ${f2(tilt)} 0 1 `
  return `M${f2(cx + dx)} ${f2(cy + dy)}${arc}${f2(cx - dx)} ${f2(cy - dy)}${arc}${f2(cx + dx)} ${f2(cy + dy)}Z`
}

// `grow` dilates the band, which is how the gutter that notches the star is cut
// from the very same numbers rather than from a second set that could drift.
export function ringPath(grow = 0) {
  const { rx, flat, tilt, w, bias, twist } = ECL
  const Ro = rx + w + grow
  const Ri = Math.max(0.6, rx - w - grow)
  const t = rad(tilt)
  return ellipse(50, 50, Ro, Ro * flat, tilt)
       + ellipse(50 + Math.sin(t) * bias, 50 - Math.cos(t) * bias, Ri, Ri * flat, tilt + twist)
}

// The band's own centreline, which is what the overture sweeps a mask along.
// Same numbers as the ring, so the reveal cannot travel a route the ring does
// not actually take.
export const ECL_SPINE = ellipse(50, 50, ECL.rx, ECL.rx * ECL.flat, ECL.tilt)

// The half-plane that keeps the near side of the ring. One object, so the
// component and the favicon string cannot drift apart.
export const NEAR = { x: -110, y: 50, width: 320, height: 160, transform: `rotate(${ECL.tilt} 50 50)` }
const nearRect = `<rect x="${NEAR.x}" y="${NEAR.y}" width="${NEAR.width}" height="${NEAR.height}" transform="${NEAR.transform}"/>`

// The two grounds the mark is ever drawn on outside this app: a light tab strip
// and a dark one. Named here rather than typed at the call site so the icon and
// any future print of it cannot disagree about which black.
export const INK = '#0A0A0C'
export const CHALK = '#F4F1EA'

// The same drawing as a bare string, for the one place React cannot reach: the
// tab's icon. Built from the exports above rather than from a second copy, so
// the drawing in the tab cannot drift from the drawing on the screen.
//
// ── the tab is not the void ─────────────────────────────────────────────────
// It used to be drawn in chalk, which is the right colour for a mark standing
// on a blue-black ground and the wrong colour for a mark standing on a browser
// tab. Chrome, Safari and Firefox all paint their tab strip near-white by
// default, and a near-white mark on it is not a subtle favicon: it is no
// favicon. The tab showed a blank square.
//
// So it is drawn in INK, and the tab's own scheme picks the other one back up:
// a browser in dark mode reports `prefers-color-scheme: dark` to the icon
// document the same way it does to a page, and the one rule below hands the
// mark back its chalk there. One drawing, two grounds, and it is visible on
// both — which is the whole job of a favicon and the only reason it exists.
//
// It returns plain markup. Percent-encoding is the CALLER's job and has to be
// done in one pass over the whole string: a `#` left raw in a data: URI starts
// a fragment and silently truncates the document at the first `fill="#fff"`,
// and a `#` pre-encoded here would be double-encoded by that pass and break
// every `url(#…)` in it. That pass also carries the `{}` of the media query,
// which decode on the other side like anything else.
export function eclipticSVG(color = INK, onDark = '') {
  const ring = ringPath()
  return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">'
    + `<defs><clipPath id="n">${nearRect}</clipPath>`
    + '<mask id="m" maskUnits="userSpaceOnUse" x="-10" y="-10" width="120" height="120">'
    + '<rect x="-10" y="-10" width="120" height="120" fill="#fff"/>'
    + `<path d="${ringPath(ECL.gutter)}" fill="#000" fill-rule="evenodd" clip-path="url(#n)"/>`
    + '</mask></defs>'
    + (onDark ? `<style>@media (prefers-color-scheme:dark){#k{fill:${onDark}}}</style>` : '')
    + `<g id="k" fill="${color}">`
    + `<path d="${ring}" fill-rule="evenodd"/>`
    + `<g mask="url(#m)"><path d="${starPath(ECL)}" transform="translate(50 50)"/></g>`
    + `<path d="${ring}" fill-rule="evenodd" clip-path="url(#n)"/></g></svg>`
}

